[[redirects]]
from = "/"
to = "/LauraMMtz/HTML/freelancer_inicio/index.html"
status = 200

[[redirects]]
from = "/freelancer_inicio/styles.css"
to = "/LauraMMtz/HTML/freelancer_inicio/css/styles.css"
status = 200

[[redirects]]
from = "/freelancer_inicio/normalize.css"
to = "/LauraMMtz/HTML/freelancer_inicio/css/normalize.css"
status = 200

[[redirects]]
from = "/frontendstore_inicio"
to = "/LauraMMtz/HTML/frontendstore_inicio/FrontEndStore_inicio/index.html"
status = 200

[[redirects]]
from = "/frontendstore_inicio/styles.css"
to = "/LauraMMtz/HTML/frontendstore_inicio/FrontEndStore_inicio/css/styles.css"
status = 200

[[redirects]]
from = "/frontendstore_inicios/normalize.css"
to = "/LauraMMtz/HTML/frontendstore_inicio/FrontEndStore_inicio/css/normalize.css"
status = 200