[[redirects]]
from = "/"
to = "/LauraMMtz/HTML/freelancer_inicio/index.html"
status = 200

[[redirects]]
from = "/freelancer_inicio/css/:splat"
to = "/LauraMMtz/HTML/freelancer_inicio/css/:splat"
status = 200

[[redirects]]
from = "/frontendstore_inicio"
to = "/LauraMMtz/HTML/frontendstore_inicio/FrontEndStore_inicio/index.html"
status = 200

[[redirects]]
from = "/frontendstore_inicio/css/:splat"
to = "/LauraMMtz/HTML/frontendstore_inicio/FrontEndStore_inicio/css/:splat"
status = 200